accounts-old/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name="user_login"),
    path('logout/', auth_views.logout_then_login, name='user_logout'),
    path('register/', views.register, name="user_register"),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        success_url='/accounts/login'), name="password_change"),
    # path('password-reset/', auth_views.PasswordResetView.as_view(success_url='/accounts/password-reset-done'), name="password_reset"),
    # path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    # path('password-reset-confirm', auth_views.PasswordResetConfirmView.as_view(success_url='/accounts/password-reset-complete'), name="password_reset_confirm"),
    # path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='blog'
urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/', views.blog_articles, name='blog_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user_register/', include('user_register.urls')),
]

urlpatterns += staticfiles_urlpatterns()

templates/accounts/register.html
{% extends "base.html" %}

{% load static %}

{% block title %}用户注册{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>注册</h1>
    <p>如已经有用户，<strong><a href="{% url 'accounts:user_login' %}">请登录</a></strong></p>
    <p>如没有用户请继续注册</p>
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="form-group">
            <label for="{{ form.username.id_for_label }}" class="col-md-5 control-label">用户名</label>
            <div class="col-md-6 text-left">{{ form.username }}</div>
        </div>
        <div class="form-group">
            <label for="{{ form.email.id_for_label }}" class="col-md-5 control-label">电子邮件</label>
            <div class="col-md-6 text-left">{{ form.email }}</div>
        </div>
        <div class="form-group">
            <label for="{{ form.password.id_for_label }}" class="col-md-5 control-label">密码</label>
            <div class="col-md-6 text-left">{{ form.password }}</div>
        </div>
        <div class="form-group">
            <label for="{{ form.password.id_for_label }}" class="col-md-5 control-label">确认密码</label>
            <div class="col-md-6 text-left">{{ form.password2 }}</div>
        </div>
        <div class="form-group">
            <label for="{{ profile.birth.id_for_label }}" class="col-md-5 control-label">生日</label>
            <div class="col-md-6 text-left">{{ profile.birth }}</div>
        </div>
        <p>格式(yyyy-mm-dd)</p>
        <div class="form-group">
            <label for="{{ profile.phone.id_for_label }}" class="col-md-5 control-label">电话</label>
            <div class="col-md-6 text-left">{{ profile.phone }}</div>
        </div>
        <input type="submit" class="btn btn-primary btn-lg" value="提交">
    </form>
</div>

{% endblock %}