blog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='blog'
urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>/', views.blog_articles, name='blog_detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user_register/', include('user_register.urls')),
]

urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-cn">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
    {% include "header.html" %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
</body>
</html>

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">&copy HVV</p>
</div>

templates/header.html
{% load static %}

<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'blog:blog_title' %}">
                <img src="{% static 'images/gbase8a.png' %}" width="200px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">首页</a> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <botton class="btn btn-default dropdown-toggle" type='button' id='dropdownMenu' data-toggle="dropdown">{{ user.username }}<span class="caret"></span></botton>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'logout' %}">退出登录</a></li>
                        </ul>
                    </div>
                </li>
                {% else %}
                <li><a href="{% url 'login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>